#!/bin/sh
set -e

compile_gsettings_schemas() {
    if command -v glib-compile-schemas >/dev/null 2>&1; then
        glib-compile-schemas /usr/share/glib-2.0/schemas
    fi
}

case "$1" in
    remove|purge|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        compile_gsettings_schemas
        ;;
esac

exit 0
